coverage:
    range: 80..100
    round: down
    precision: 2

    status:
        project:
            default: false
            app:
                paths:
                    - "!test/"
                target: auto
                threshold: 1%
                if_ci_failed: error
            tests:
                paths: 
                    - "test/"
                target: 100%
                if_ci_failed: error

ignore:
    - "json/*"
