coverage:
    range: 80..100
    round: down
    precision: 2

    status:
        project:
            default:
                enabled: yes
                target: 80%

                threshhold: null
                if_not_found: success
                if_ci_failed: error
            patch:
                default:
                    enabled: no

